# Generated by Django 2.2.1 on 2019-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('author_ip', models.GenericIPAddressField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('done_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
